/* 
 * ata
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
	/// <summary>
	/// Represents a collection of functions to interact with the API endpoints
	/// </summary>
	public interface IValidationTemplateApi : IApiAccessor
	{
		#region Synchronous Operations
		/// <summary>
		/// Create a new instance of the model and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>ValidationTemplate</returns>
		ValidationTemplate ValidationTemplateCreate (ValidationTemplate data = null);

		/// <summary>
		/// Create a new instance of the model and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		ApiResponse<ValidationTemplate> ValidationTemplateCreateWithHttpInfo (ValidationTemplate data = null);
		/// <summary>
		/// Delete a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>Object</returns>
		Object ValidationTemplateDeleteById (string id);

		/// <summary>
		/// Delete a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>ApiResponse of Object</returns>
		ApiResponse<Object> ValidationTemplateDeleteByIdWithHttpInfo (string id);
		/// <summary>
		/// Find all instances of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>List&lt;ValidationTemplate&gt;</returns>
		List<ValidationTemplate> ValidationTemplateFind (string filter = null);

		/// <summary>
		/// Find all instances of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>ApiResponse of List&lt;ValidationTemplate&gt;</returns>
		ApiResponse<List<ValidationTemplate>> ValidationTemplateFindWithHttpInfo (string filter = null);
		/// <summary>
		/// Find a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>ValidationTemplate</returns>
		ValidationTemplate ValidationTemplateFindById (string id, string filter = null);

		/// <summary>
		/// Find a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		ApiResponse<ValidationTemplate> ValidationTemplateFindByIdWithHttpInfo (string id, string filter = null);
		/// <summary>
		/// Find first instance of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>ValidationTemplate</returns>
		ValidationTemplate ValidationTemplateFindOne (string filter = null);

		/// <summary>
		/// Find first instance of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		ApiResponse<ValidationTemplate> ValidationTemplateFindOneWithHttpInfo (string filter = null);
		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ValidationTemplate</returns>
		ValidationTemplate ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesid (string id, ValidationTemplate data = null);

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		ApiResponse<ValidationTemplate> ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidWithHttpInfo (string id, ValidationTemplate data = null);
		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ValidationTemplate</returns>
		ValidationTemplate ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesid (string id, ValidationTemplate data = null);

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		ApiResponse<ValidationTemplate> ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidWithHttpInfo (string id, ValidationTemplate data = null);
		#endregion Synchronous Operations
		#region Asynchronous Operations
		/// <summary>
		/// Create a new instance of the model and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplateCreateAsync (ValidationTemplate data = null);

		/// <summary>
		/// Create a new instance of the model and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplateCreateAsyncWithHttpInfo (ValidationTemplate data = null);
		/// <summary>
		/// Delete a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>Task of Object</returns>
		System.Threading.Tasks.Task<Object> ValidationTemplateDeleteByIdAsync (string id);

		/// <summary>
		/// Delete a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>Task of ApiResponse (Object)</returns>
		System.Threading.Tasks.Task<ApiResponse<Object>> ValidationTemplateDeleteByIdAsyncWithHttpInfo (string id);
		/// <summary>
		/// Find all instances of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of List&lt;ValidationTemplate&gt;</returns>
		System.Threading.Tasks.Task<List<ValidationTemplate>> ValidationTemplateFindAsync (string filter = null);

		/// <summary>
		/// Find all instances of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of ApiResponse (List&lt;ValidationTemplate&gt;)</returns>
		System.Threading.Tasks.Task<ApiResponse<List<ValidationTemplate>>> ValidationTemplateFindAsyncWithHttpInfo (string filter = null);
		/// <summary>
		/// Find a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplateFindByIdAsync (string id, string filter = null);

		/// <summary>
		/// Find a model instance by {{id}} from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplateFindByIdAsyncWithHttpInfo (string id, string filter = null);
		/// <summary>
		/// Find first instance of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplateFindOneAsync (string filter = null);

		/// <summary>
		/// Find first instance of the model matched by filter from the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplateFindOneAsyncWithHttpInfo (string filter = null);
		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidAsync (string id, ValidationTemplate data = null);

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidAsyncWithHttpInfo (string id, ValidationTemplate data = null);
		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidAsync (string id, ValidationTemplate data = null);

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source.
		/// </summary>
		/// <remarks>
		/// 
		/// </remarks>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidAsyncWithHttpInfo (string id, ValidationTemplate data = null);
		#endregion Asynchronous Operations
	}

	/// <summary>
	/// Represents a collection of functions to interact with the API endpoints
	/// </summary>
	public partial class ValidationTemplateApi : IValidationTemplateApi
	{
		private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

		/// <summary>
		/// Initializes a new instance of the <see cref="ValidationTemplateApi"/> class.
		/// </summary>
		/// <returns></returns>
		public ValidationTemplateApi(String basePath)
		{
			this.Configuration = new Configuration(new ApiClient(basePath));

			ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

			// ensure API client has configuration ready
			if (Configuration.ApiClient.Configuration == null)
			{
				this.Configuration.ApiClient.Configuration = this.Configuration;
			}
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ValidationTemplateApi"/> class
		/// using Configuration object
		/// </summary>
		/// <param name="configuration">An instance of Configuration</param>
		/// <returns></returns>
		public ValidationTemplateApi(Configuration configuration = null)
		{
			if (configuration == null) // use the default one in Configuration
				this.Configuration = Configuration.Default;
			else
				this.Configuration = configuration;

			ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

			// ensure API client has configuration ready
			if (Configuration.ApiClient.Configuration == null)
			{
				this.Configuration.ApiClient.Configuration = this.Configuration;
			}
		}

		/// <summary>
		/// Gets the base path of the API client.
		/// </summary>
		/// <value>The base path</value>
		public String GetBasePath()
		{
			return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
		}

		/// <summary>
		/// Sets the base path of the API client.
		/// </summary>
		/// <value>The base path</value>
		[Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
		public void SetBasePath(String basePath)
		{
			// do nothing
		}

		/// <summary>
		/// Gets or sets the configuration object
		/// </summary>
		/// <value>An instance of the Configuration</value>
		public Configuration Configuration {get; set;}

		/// <summary>
		/// Provides a factory method hook for the creation of exceptions.
		/// </summary>
		public IO.Swagger.Client.ExceptionFactory ExceptionFactory
		{
			get
			{
				if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
				{
					throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
				}
				return _exceptionFactory;
			}
			set { _exceptionFactory = value; }
		}

		/// <summary>
		/// Gets the default header.
		/// </summary>
		/// <returns>Dictionary of HTTP header</returns>
		[Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
		public Dictionary<String, String> DefaultHeader()
		{
			return this.Configuration.DefaultHeader;
		}

		/// <summary>
		/// Add default header.
		/// </summary>
		/// <param name="key">Header field name.</param>
		/// <param name="value">Header field value.</param>
		/// <returns></returns>
		[Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
		public void AddDefaultHeader(string key, string value)
		{
			this.Configuration.AddDefaultHeader(key, value);
		}

		/// <summary>
		/// Create a new instance of the model and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>ValidationTemplate</returns>
		public ValidationTemplate ValidationTemplateCreate (ValidationTemplate data = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = ValidationTemplateCreateWithHttpInfo(data);
			 return localVarResponse.Data;
		}

		/// <summary>
		/// Create a new instance of the model and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		public ApiResponse< ValidationTemplate > ValidationTemplateCreateWithHttpInfo (ValidationTemplate data = null)
		{

			var localVarPath = "/validationTemplates";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (data != null && data.GetType() != typeof(byte[]))
			{
				localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
			}
			else
			{
				localVarPostBody = data; // byte array
			}


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
				Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateCreate", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Create a new instance of the model and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		public async System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplateCreateAsync (ValidationTemplate data = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = await ValidationTemplateCreateAsyncWithHttpInfo(data);
			 return localVarResponse.Data;

		}

		/// <summary>
		/// Create a new instance of the model and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="data">Model instance data (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		public async System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplateCreateAsyncWithHttpInfo (ValidationTemplate data = null)
		{

			var localVarPath = "/validationTemplates";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (data != null && data.GetType() != typeof(byte[]))
			{
				localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
			}
			else
			{
				localVarPostBody = data; // byte array
			}


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
				Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateCreate", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Delete a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>Object</returns>
		public Object ValidationTemplateDeleteById (string id)
		{
			 ApiResponse<Object> localVarResponse = ValidationTemplateDeleteByIdWithHttpInfo(id);
			 return localVarResponse.Data;
		}

		/// <summary>
		/// Delete a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>ApiResponse of Object</returns>
		public ApiResponse< Object > ValidationTemplateDeleteByIdWithHttpInfo (string id)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplateDeleteById");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
				Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateDeleteById", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<Object>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
			
		}

		/// <summary>
		/// Delete a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>Task of Object</returns>
		public async System.Threading.Tasks.Task<Object> ValidationTemplateDeleteByIdAsync (string id)
		{
			 ApiResponse<Object> localVarResponse = await ValidationTemplateDeleteByIdAsyncWithHttpInfo(id);
			 return localVarResponse.Data;

		}

		/// <summary>
		/// Delete a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <returns>Task of ApiResponse (Object)</returns>
		public async System.Threading.Tasks.Task<ApiResponse<Object>> ValidationTemplateDeleteByIdAsyncWithHttpInfo (string id)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplateDeleteById");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
				Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateDeleteById", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<Object>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
			
		}

		/// <summary>
		/// Find all instances of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>List&lt;ValidationTemplate&gt;</returns>
		public List<ValidationTemplate> ValidationTemplateFind (string filter = null)
		{
			 ApiResponse<List<ValidationTemplate>> localVarResponse = ValidationTemplateFindWithHttpInfo(filter);
			 return localVarResponse.Data;
		}

		/// <summary>
		/// Find all instances of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>ApiResponse of List&lt;ValidationTemplate&gt;</returns>
		public ApiResponse< List<ValidationTemplate> > ValidationTemplateFindWithHttpInfo (string filter = null)
		{

			var localVarPath = "/validationTemplates";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
				Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateFind", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<List<ValidationTemplate>>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(List<ValidationTemplate>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ValidationTemplate>)));
			
		}

		/// <summary>
		/// Find all instances of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of List&lt;ValidationTemplate&gt;</returns>
		public async System.Threading.Tasks.Task<List<ValidationTemplate>> ValidationTemplateFindAsync (string filter = null)
		{
			 ApiResponse<List<ValidationTemplate>> localVarResponse = await ValidationTemplateFindAsyncWithHttpInfo(filter);
			 return localVarResponse.Data;

		}

		/// <summary>
		/// Find all instances of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of ApiResponse (List&lt;ValidationTemplate&gt;)</returns>
		public async System.Threading.Tasks.Task<ApiResponse<List<ValidationTemplate>>> ValidationTemplateFindAsyncWithHttpInfo (string filter = null)
		{

			var localVarPath = "/validationTemplates";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
				Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateFind", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<List<ValidationTemplate>>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(List<ValidationTemplate>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ValidationTemplate>)));
			
		}

		/// <summary>
		/// Find a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>ValidationTemplate</returns>
		public ValidationTemplate ValidationTemplateFindById (string id, string filter = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = ValidationTemplateFindByIdWithHttpInfo(id, filter);
			 return localVarResponse.Data;
		}

		/// <summary>
		/// Find a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		public ApiResponse< ValidationTemplate > ValidationTemplateFindByIdWithHttpInfo (string id, string filter = null)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplateFindById");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
			if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
				Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateFindById", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Find a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		public async System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplateFindByIdAsync (string id, string filter = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = await ValidationTemplateFindByIdAsyncWithHttpInfo(id, filter);
			 return localVarResponse.Data;

		}

		/// <summary>
		/// Find a model instance by {{id}} from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">Model id</param>
		/// <param name="filter">Filter defining fields and include (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		public async System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplateFindByIdAsyncWithHttpInfo (string id, string filter = null)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplateFindById");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
			if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
				Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateFindById", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Find first instance of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>ValidationTemplate</returns>
		public ValidationTemplate ValidationTemplateFindOne (string filter = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = ValidationTemplateFindOneWithHttpInfo(filter);
			 return localVarResponse.Data;
		}

		/// <summary>
		/// Find first instance of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		public ApiResponse< ValidationTemplate > ValidationTemplateFindOneWithHttpInfo (string filter = null)
		{

			var localVarPath = "/validationTemplates/findOne";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
				Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateFindOne", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Find first instance of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		public async System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplateFindOneAsync (string filter = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = await ValidationTemplateFindOneAsyncWithHttpInfo(filter);
			 return localVarResponse.Data;

		}

		/// <summary>
		/// Find first instance of the model matched by filter from the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="filter">Filter defining fields, where, include, order, offset, and limit (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		public async System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplateFindOneAsyncWithHttpInfo (string filter = null)
		{

			var localVarPath = "/validationTemplates/findOne";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (filter != null) localVarQueryParams.Add("filter", Configuration.ApiClient.ParameterToString(filter)); // query parameter


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
				Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplateFindOne", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ValidationTemplate</returns>
		public ValidationTemplate ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesid (string id, ValidationTemplate data = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidWithHttpInfo(id, data);
			 return localVarResponse.Data;
		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		public ApiResponse< ValidationTemplate > ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidWithHttpInfo (string id, ValidationTemplate data = null)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesid");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
			if (data != null && data.GetType() != typeof(byte[]))
			{
				localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
			}
			else
			{
				localVarPostBody = data; // byte array
			}


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
				Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesid", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		public async System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidAsync (string id, ValidationTemplate data = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = await ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidAsyncWithHttpInfo(id, data);
			 return localVarResponse.Data;

		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		public async System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesidAsyncWithHttpInfo (string id, ValidationTemplate data = null)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesid");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
			if (data != null && data.GetType() != typeof(byte[]))
			{
				localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
			}
			else
			{
				localVarPostBody = data; // byte array
			}


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
				Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplatePrototypeUpdateAttributesPatchValidationTemplatesid", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ValidationTemplate</returns>
		public ValidationTemplate ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesid (string id, ValidationTemplate data = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidWithHttpInfo(id, data);
			 return localVarResponse.Data;
		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>ApiResponse of ValidationTemplate</returns>
		public ApiResponse< ValidationTemplate > ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidWithHttpInfo (string id, ValidationTemplate data = null)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesid");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
			if (data != null && data.GetType() != typeof(byte[]))
			{
				localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
			}
			else
			{
				localVarPostBody = data; // byte array
			}


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
				Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesid", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ValidationTemplate</returns>
		public async System.Threading.Tasks.Task<ValidationTemplate> ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidAsync (string id, ValidationTemplate data = null)
		{
			 ApiResponse<ValidationTemplate> localVarResponse = await ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidAsyncWithHttpInfo(id, data);
			 return localVarResponse.Data;

		}

		/// <summary>
		/// Patch attributes for a model instance and persist it into the data source. 
		/// </summary>
		/// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
		/// <param name="id">validationTemplate id</param>
		/// <param name="data">An object of model property name/value pairs (optional)</param>
		/// <returns>Task of ApiResponse (ValidationTemplate)</returns>
		public async System.Threading.Tasks.Task<ApiResponse<ValidationTemplate>> ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesidAsyncWithHttpInfo (string id, ValidationTemplate data = null)
		{
			// verify the required parameter 'id' is set
			if (id == null)
				throw new ApiException(400, "Missing required parameter 'id' when calling ValidationTemplateApi->ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesid");

			var localVarPath = "/validationTemplates/{id}";
			var localVarPathParams = new Dictionary<String, String>();
			var localVarQueryParams = new Dictionary<String, String>();
			var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
			var localVarFormParams = new Dictionary<String, String>();
			var localVarFileParams = new Dictionary<String, FileParameter>();
			Object localVarPostBody = null;

			// to determine the Content-Type header
			String[] localVarHttpContentTypes = new String[] {
				"application/json", 
				"application/x-www-form-urlencoded", 
				"application/xml", 
				"text/xml"
			};
			String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

			// to determine the Accept header
			String[] localVarHttpHeaderAccepts = new String[] {
				"application/json", 
				"application/xml", 
				"text/xml", 
				"application/javascript", 
				"text/javascript"
			};
			String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
			if (localVarHttpHeaderAccept != null)
				localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

			// set "format" to json by default
			// e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
			localVarPathParams.Add("format", "json");
			if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
			if (data != null && data.GetType() != typeof(byte[]))
			{
				localVarPostBody = Configuration.ApiClient.Serialize(data); // http body (model) parameter
			}
			else
			{
				localVarPostBody = data; // byte array
			}


			// make the HTTP request
			IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
				Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
				localVarPathParams, localVarHttpContentType);

			int localVarStatusCode = (int) localVarResponse.StatusCode;

			if (ExceptionFactory != null)
			{
				Exception exception = ExceptionFactory("ValidationTemplatePrototypeUpdateAttributesPutValidationTemplatesid", localVarResponse);
				if (exception != null) throw exception;
			}

			return new ApiResponse<ValidationTemplate>(localVarStatusCode,
				localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
				(ValidationTemplate) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ValidationTemplate)));
			
		}

	}
}
